name: rzls
description: |
  Razor is a markup syntax for adding server-side logic to web pages.
  This package contains a Razor language server.
homepage: https://github.com/dotnet/razor
licenses:
  - MIT
languages:
  - C#
categories:
  - LSP
source:
  # renovate:versioning=loose
  id: pkg:github/Crashdummyy/rzls@9.0.0-preview.24557.11
  asset:
    - target: darwin_x64
      file: rzls.osx-x64.zip:libexec/
    - target: darwin_arm64
      file: rzls.osx-arm64.zip:libexec/
    - target: linux_x64
      file: rzls.linux-x64.zip:libexec/
    - target: linux_arm64
      file: rzls.linux-arm64.zip:libexec/
    - target: win_x64
      file: rzls.win-x64.zip:libexec/
    - target: win_arm64
      file: rzls.win-arm64.zip:libexec/
bin:
  rzls: dotnet:libexec/rzls.dll
